name: Benchmark

on: [push, pull_request]

jobs:
  run-evaluation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Environment Variable Using Secret
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Evaluate Train | WithPlotType
        run: python src/evaluate.py --complexity WithPlotType --mode train

      - name: Evaluate Train | WithoutPlotType
        run: python src/evaluate.py --complexity WithoutPlotType --mode train
